# Generated by Django 3.1.5 on 2022-02-20 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_gallery_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model3d',
            options={'verbose_name_plural': 'model3ds'},
        ),
    ]
