# Generated by Django 3.1.5 on 2022-02-20 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_gallery_viewer', '0002_auto_20220220_0301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model3d',
            options={'verbose_name_plural': 'Model_3Ds'},
        ),
    ]
