# Generated by Django 3.1.5 on 2022-02-20 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_gallery_viewer', '0003_auto_20220220_0305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model3d',
            old_name='modelglb',
            new_name='model_glb',
        ),
    ]
